language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

before_script:
  - rustup component add clippy rustfmt
script:
  - cargo clippy -- -D warnings
  - cargo fmt -- --check
  - cargo test
